#!/bin/sh

rm -f log_simserver
nohup python -m simserver.run_simserver /tmp/server>log_simserver 2>&1 &
sleep 5

rm -f log_manager
nohup ./manage.py runserver 0.0.0.0:8080 >log_manager 2>&1 &
sleep 5

rm -f log_proc
nohup python /opt/projects/git_source/scrapy-board/scrapy_board/process_items.py >log_proc 2>&1 &



